title: Slides
remote_theme: RMWinslow/JTD-RMW
author: Robert Winslow
description: "Markdown Slides using remark.js"
search_enabled: true

plugins:
  - jekyll-sitemap

compress_html:
  ignore:
    envs: all

